---
- hosts: all
  gather_facts: no
  become: true
  become_method: sudo

  tasks:

    - name: Fetch GPG Key
      shell:
        cmd: sudo curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | sudo gpg --dearmor --yes -o /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Fix permissions issues due to masking
      shell:
        cmd: sudo chmod a+r /usr/share/keyrings/docker-archive-keyring.gpg
  
    - name: Install base packages
      apt:
        update_cache: yes
        pkg:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
    
    - name: Add sources.list for docker
      shell:
        cmd: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Install docker packages
      apt:
        update_cache: yes
        pkg:
          - docker-ce 
          - docker-ce-cli 
          - containerd.io
        
    - name: enable and start docker service
      service:
        name: docker
        state: started
        enabled: yes
